[unix_http_server]
file=/tmp/supervisor.sock   ; (the path to the socket file)

[supervisord]
logfile=/tmp/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/tmp/supervisord.pid
nodaemon=true
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock ; use a unix:// URL  for a unix socket

[program:remote_syslog]
command=remote_syslog -D -c "/etc/logs_config.yml"
user=root
group=root
autostart=true
autorestart=true
redirect_stderr=true

[program:node]
command=node --max-old-space-size=512 /usr/src/app/server.js
redirect_stderr=true
stdout_logfile=/tmp/cert_app.log
autostart=true
autorestart=true
