export const FETCH_USER_DETAILS_FROM_USER_EMAIL = `SELECT * FROM USER WHERE EMAIL = ? LIMIT 1`;
export const GET_TRENDING_DISCUSSIONS = `WITH COMMENT_COUNT AS ( SELECT COUNT(ID) AS COUNT, POST_ID FROM COMMENTS GROUP BY (POST_ID) ), 
        VOTE_COUNT AS ( SELECT COUNT(ID) AS COUNT, POST_ID FROM VOTES GROUP BY (POST_ID)), 
        TAG_VAL AS ( SELECT LISTAGG(TAG_NAME, '//') AS TAGS, POST_ID FROM TAGS WHERE IS_DELETED = FALSE GROUP BY (POST_ID) ), 
        SAVEDPOST AS ( SELECT TRUE AS IS_BOOKMARKED, POST_ID FROM SAVED_POSTS WHERE USER_ID = ? AND IS_DELETED = FALSE ), 
        VOTEPOST AS ( SELECT TRUE AS IS_VOTED, POST_ID FROM VOTES WHERE USER_ID = ?)   
        SELECT PO.ID, PO.TITLE, PO.DESCRIPTION, CA.ID AS CATEGORY_ID, CA.NAME AS CATEGORY, NVL(COM.COUNT,0) AS COMMENT_COUNT, 
            NVL(VO.COUNT,0) AS VOTE_COUNT, US.USER_ID,  NVL(SP.IS_BOOKMARKED, FALSE) AS IS_BOOKMARKED, 
            NVL(VP.IS_VOTED, FALSE) AS IS_VOTED, NVL(TV.TAGS,'') as TAGS, (US.FIRSTNAME || ' ' || US.LASTNAME) AS USER_NAME, 
            PO.CREATED_AT, TS.STATUS, COUNT(PO.ID) OVER ( ORDER BY PO.ID RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) TOTAL_COUNT 
        FROM POSTS PO 
        LEFT JOIN CATEGORY CA ON PO.CATEGORY_ID = CA.ID 
        LEFT JOIN VOTE_COUNT VO ON PO.ID = VO.POST_ID 
        LEFT JOIN COMMENT_COUNT COM ON PO.ID = COM.POST_ID 
        LEFT JOIN USER US ON PO.USER_ID = US.USER_ID 
        LEFT JOIN TAG_VAL TV ON PO.ID = TV.POST_ID 
        LEFT JOIN SAVEDPOST SP ON PO.ID = SP.POST_ID 
        LEFT JOIN VOTEPOST VP ON PO.ID = VP.POST_ID   
        LEFT JOIN TICKET_STATUS TS ON PO.STATUS_ID = TS.ID 
        WHERE PO.IS_DELETED = 0 
        ORDER BY NVL(VO.COUNT, 0) DESC, NVL(COM.COUNT,0) DESC 
        LIMIT ? OFFSET ?`;
export const GET_CATEGORY_COUNT = `SELECT 0 AS ID, 'All' AS NAME, COUNT(ID) AS COUNT FROM POSTS WHERE IS_DELETED = 0
        UNION ALL
        SELECT CA.ID, CA.NAME, COUNT(PO.CATEGORY_ID) AS COUNT
        FROM CATEGORY CA LEFT JOIN POSTS PO ON CA.ID = PO.CATEGORY_ID AND PO.IS_DELETED = 0 GROUP BY (CA.ID, CA.NAME, PO.CATEGORY_ID)
        UNION ALL
        SELECT (SELECT MAX(ID)+1 FROM CATEGORY) AS ID, 'FAQs' AS NAME, COUNT(ID) FROM POSTS WHERE IS_FAQ = 1 AND IS_DELETED = 0
        ORDER BY ID`;
export const GET_STATUS_COUNT_DATA = `SELECT 0 AS ID, 'All' AS STATUS, COUNT(ID) AS COUNT FROM POSTS WHERE IS_DELETED = 0 
        UNION ALL SELECT CA.ID, CA.STATUS, COUNT(PO.STATUS_ID) AS COUNT 
        FROM TICKET_STATUS CA 
        LEFT JOIN POSTS PO ON CA.ID = PO.STATUS_ID AND PO.IS_DELETED = 0 
        GROUP BY (CA.ID, CA.STATUS, PO.STATUS_ID) ORDER BY ID`;
export const GET_STATUS_COUNT_DATA_BY_CATEGORY = `SELECT 0 AS ID, 'All' AS STATUS, COUNT(ID) AS COUNT FROM POSTS WHERE IS_DELETED = 0 AND CATEGORY_ID = ? UNION ALL 
SELECT CA.ID, CA.STATUS, COUNT(PO.STATUS_ID) AS COUNT FROM TICKET_STATUS CA LEFT JOIN POSTS PO ON CA.ID = PO.STATUS_ID AND PO.IS_DELETED = 0 AND PO.CATEGORY_ID = ?
GROUP BY (CA.ID, CA.STATUS, PO.STATUS_ID) ORDER BY ID;`
export const GET_ALL_DISCUSSIONS = `WITH COMMENT_COUNT AS ( SELECT COUNT(ID) AS COUNT, POST_ID FROM COMMENTS WHERE IS_DELETED = false GROUP BY (POST_ID) ), 
        ADMIN_COMMENT_COUNT AS ( SELECT COUNT(CM.ID) AS COMMENT_COUNT, CM.POST_ID FROM COMMENTS CM LEFT JOIN USERINAGENCY US ON CM.USER_ID = US.USER_ID WHERE US.ROLE_ID = 1 GROUP BY (CM.POST_ID) ),
        VOTE_COUNT AS ( SELECT COUNT(ID) AS COUNT, POST_ID FROM VOTES GROUP BY (POST_ID)), 
        TAG_VAL AS ( SELECT LISTAGG(TAG_NAME, '//') AS TAGS, POST_ID FROM TAGS WHERE IS_DELETED = FALSE GROUP BY (POST_ID) ), 
        SAVEDPOST AS ( SELECT TRUE AS IS_BOOKMARKED, POST_ID FROM SAVED_POSTS WHERE USER_ID = ? AND IS_DELETED = FALSE ), 
        VOTEPOST AS ( SELECT TRUE AS IS_VOTED, POST_ID FROM VOTES WHERE USER_ID = ?)   
        SELECT PO.ID, PO.TITLE, PO.DESCRIPTION, CA.ID AS CATEGORY_ID, CA.NAME AS CATEGORY, NVL(COM.COUNT,0) AS COMMENT_COUNT, 
            NVL(VO.COUNT,0) AS VOTE_COUNT, US.USER_ID,  NVL(SP.IS_BOOKMARKED, FALSE) AS IS_BOOKMARKED, NVL(ACM.COMMENT_COUNT, 0) AS ADMIN_COMMENT_COUNT,
            NVL(VP.IS_VOTED, FALSE) AS IS_VOTED, NVL(TV.TAGS,'') as TAGS, (US.FIRSTNAME || ' ' || US.LASTNAME) AS USER_NAME, 
            PO.CREATED_AT, TS.STATUS, COUNT(PO.ID) OVER ( ORDER BY PO.ID RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) TOTAL_COUNT 
        FROM POSTS PO 
        LEFT JOIN CATEGORY CA ON PO.CATEGORY_ID = CA.ID 
        LEFT JOIN VOTE_COUNT VO ON PO.ID = VO.POST_ID 
        LEFT JOIN COMMENT_COUNT COM ON PO.ID = COM.POST_ID 
        LEFT JOIN ADMIN_COMMENT_COUNT ACM ON PO.ID = ACM.POST_ID 
        LEFT JOIN USER US ON PO.USER_ID = US.USER_ID 
        LEFT JOIN TAG_VAL TV ON PO.ID = TV.POST_ID 
        LEFT JOIN SAVEDPOST SP ON PO.ID = SP.POST_ID 
        LEFT JOIN VOTEPOST VP ON PO.ID = VP.POST_ID   
        LEFT JOIN TICKET_STATUS TS ON PO.STATUS_ID = TS.ID 
        WHERE PO.IS_DELETED = 0 `;
export const SEARCH_DISCUSSION = `WITH COMMENT_COUNT AS ( SELECT COUNT(ID) AS COUNT, POST_ID FROM COMMENTS GROUP BY (POST_ID) ), 
        VOTE_COUNT AS ( SELECT COUNT(ID) AS COUNT, POST_ID FROM VOTES GROUP BY (POST_ID)), 
        TAG_VAL AS ( SELECT LISTAGG(TAG_NAME, '//') AS TAGS, POST_ID FROM TAGS WHERE IS_DELETED = FALSE GROUP BY (POST_ID) ), 
        SAVEDPOST AS ( SELECT TRUE AS IS_BOOKMARKED, POST_ID FROM SAVED_POSTS WHERE USER_ID = ? AND IS_DELETED = FALSE ), 
        VOTEPOST AS ( SELECT TRUE AS IS_VOTED, POST_ID FROM VOTES WHERE USER_ID = ?)   
        SELECT PO.ID, PO.TITLE, PO.DESCRIPTION, CA.ID AS CATEGORY_ID, CA.NAME AS CATEGORY, NVL(COM.COUNT,0) AS COMMENT_COUNT, 
            NVL(VO.COUNT,0) AS VOTE_COUNT, US.USER_ID,  NVL(SP.IS_BOOKMARKED, FALSE) AS IS_BOOKMARKED, NVL(VP.IS_VOTED, FALSE) AS IS_VOTED, 
            NVL(TV.TAGS,'') as TAGS, (US.FIRSTNAME || ' ' || US.LASTNAME) AS USER_NAME, PO.CREATED_AT, TS.STATUS, COUNT(PO.ID) OVER ( ORDER BY PO.ID RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) TOTAL_COUNT 
        FROM POSTS PO 
        LEFT JOIN CATEGORY CA ON PO.CATEGORY_ID = CA.ID 
        LEFT JOIN VOTE_COUNT VO ON PO.ID = VO.POST_ID 
        LEFT JOIN COMMENT_COUNT COM ON PO.ID = COM.POST_ID 
        LEFT JOIN USER US ON PO.USER_ID = US.USER_ID 
        LEFT JOIN TAG_VAL TV ON PO.ID = TV.POST_ID 
        LEFT JOIN SAVEDPOST SP ON PO.ID = SP.POST_ID 
        LEFT JOIN VOTEPOST VP ON PO.ID = VP.POST_ID   
        LEFT JOIN TICKET_STATUS TS ON PO.STATUS_ID = TS.ID 
        WHERE (TRIM(LOWER(NVL(TV.TAGS,''))) LIKE ? OR TRIM(LOWER(PO.TITLE)) LIKE ? OR TRIM(LOWER(CA.NAME)) LIKE ?) 
            AND PO.IS_DELETED = 0 
        ORDER BY PO.CREATED_AT ASC LIMIT ? OFFSET ?`;
export const GET_DISCUSSION_USING_ID = `SELECT * FROM POSTS WHERE ID = ?`;
export const GET_CATEGORY_DATA_USING_ID = `SELECT * FROM CATEGORY WHERE ID = ?`;
export const GET_CATEGORY_DATA_USING_NAME = `SELECT * FROM CATEGORY WHERE NAME = TRIM(?)`;
export const GET_STATUS_DATA_USING_ID = `SELECT * FROM TICKET_STATUS WHERE ID = ?`;
export const GET_STATUS_DATA_USING_NAME = `SELECT * FROM TICKET_STATUS WHERE TRIM(LOWER(STATUS)) = TRIM(LOWER(?))`;
export const INSERT_STATUS = `INSERT INTO TICKET_STATUS(STATUS) VALUES(?)`;
export const GET_VOTE_COUNT_FOR_POST_ID = `SELECT COUNT(*) AS VOTE_COUNT FROM VOTES WHERE POST_ID = ?`;
export const GET_ALL_COMMENTS_FOR_POST_ID = `SELECT COM.ID, US.USER_ID, (US.FIRSTNAME || ' ' || US.LASTNAME) AS USER_NAME, 
            COM.POST_ID, COM.DESCRIPTION as DESCRIPTION_AS_BYTE, COM.CREATED_AT, COM.IS_DELETED, AF.IS_USEFUL, AF.FEEDBACK 
        FROM COMMENTS COM 
        LEFT JOIN USER US ON COM.USER_ID = US.USER_ID 
        LEFT JOIN ANSWERS_FEEDBACK AF ON COM.ID = AF.COMMENT_ID AND AF.USER_ID = ? 
        WHERE COM.POST_ID = ? AND COM.IS_DELETED = false ORDER BY COM.CREATED_AT DESC`;
export const DELETE_COMMENT_FOR_POST_BY_ID = `UPDATE COMMENTS SET IS_DELETED = true WHERE ID = ? AND POST_ID = ?`;
export const GET_TAGS_FOR_POST_ID = `SELECT * FROM TAGS WHERE POST_ID = ? AND IS_DELETED = false`;
export const CHECK_SAVED_POST_FOR_USER = `SELECT * FROM SAVED_POSTS WHERE USER_ID = ? AND POST_ID = ? AND IS_DELETED = false`;
export const GET_USER_DATA_USING_ID = `SELECT * FROM USER WHERE USER_ID = ?`;
export const GET_USER_DATA_USING_EMAIL = `SELECT * FROM USER WHERE EMAIL = ?`;
export const GET_USER_ID_USING_EMAIL = `SELECT USER_ID AS ID FROM USER WHERE EMAIL = ?`;
export const GET_USER_IN_AGENCY_DATA_USING_ID = `SELECT * FROM USERINAGENCY WHERE USER_ID = ?`;
export const GET_AGENCY_DATA_USING_ID = `SELECT * FROM AGENCY WHERE AGENCY_ID = ?`;
export const GET_ROLE_DATA_USING_ID = `SELECT * FROM ROLE WHERE ROLE_ID = ?`;
export const INSERT_INTO_COMMENT = `INSERT INTO COMMENTS(USER_ID, POST_ID, DESCRIPTION, IS_DELETED, CREATED_AT) VALUES(?, ?, CAST(? AS BLOB), ?, ?)`;
export const UPDATE_INTO_COMMENT = `UPDATE COMMENTS SET DESCRIPTION = CAST(? AS BLOB) WHERE POST_ID = ? AND ID = ?`;
export const MERGE_INTO_ANSWERS_FEEDBACK = `MERGE INTO ANSWERS_FEEDBACK AF
        USING (VALUES(?,?,?,?,?)) AS AFDATA(ID, USER_ID, COMMENT_ID, IS_USEFUL, FEEDBACK)
        ON AFDATA.ID = AF.ID
        WHEN MATCHED THEN UPDATE SET
            AF.USER_ID = AFDATA.USER_ID, 
            AF.COMMENT_ID = AFDATA.COMMENT_ID, 
            AF.IS_USEFUL = AFDATA.IS_USEFUL, 
            AF.FEEDBACK = AFDATA.FEEDBACK
        WHEN NOT MATCHED THEN INSERT(USER_ID, COMMENT_ID, IS_USEFUL, FEEDBACK) VALUES(AFDATA.USER_ID, AFDATA.COMMENT_ID, AFDATA.IS_USEFUL, AFDATA.FEEDBACK)`;
export const GET_COMMENT_FEEDBACK_USING_COMMENT_ID = `SELECT AF.ID, US.USER_ID, AF.COMMENT_ID, AF.IS_USEFUL, AF.FEEDBACK, (US.FIRSTNAME || ' ' || US.LASTNAME) AS USER_NAME
        FROM ANSWERS_FEEDBACK AF
        LEFT JOIN USER US ON AF.USER_ID = US.USER_ID
        WHERE AF.COMMENT_ID = ?`;
export const MERGE_INTO_NOTIFICATION = `MERGE INTO NOTIFICATIONS AF
        USING (VALUES(?,?,?,?,?,?)) AS AFDATA(ID, USER_ID, POST_ID, DESCRIPTION, TRIGGER_TIME, IS_READ)
        ON AFDATA.ID = AF.ID
        WHEN MATCHED THEN UPDATE SET
            AF.USER_ID = AFDATA.USER_ID, 
            AF.POST_ID = AFDATA.POST_ID, 
            AF.DESCRIPTION = AFDATA.DESCRIPTION, 
            AF.TRIGGER_TIME = AFDATA.TRIGGER_TIME, 
            AF.IS_READ = AFDATA.IS_READ
        WHEN NOT MATCHED THEN INSERT(USER_ID, POST_ID, DESCRIPTION, TRIGGER_TIME, IS_READ) VALUES( AFDATA.USER_ID, AFDATA.POST_ID, AFDATA.DESCRIPTION, AFDATA.TRIGGER_TIME, AFDATA.IS_READ)`;
export const GET_USER_UNREAD_NOTIFICATIONS = `SELECT * FROM NOTIFICATIONS WHERE USER_ID = ? AND IS_READ = 0 ORDER BY TRIGGER_TIME DESC`;
export const GET_USER_ALL_NOTIFICATIONS = `SELECT * FROM NOTIFICATIONS WHERE USER_ID = ? ORDER BY TRIGGER_TIME DESC`;
export const UPDATE_USER_NOTIFICATION_READ = `UPDATE NOTIFICATIONS SET IS_READ = 1 WHERE id = ?`;
export const UPDATE_USER__ALL_NOTIFICATION_READ = `UPDATE NOTIFICATIONS SET IS_READ = 1 WHERE USER_ID = ?`;
export const DELETE_NOTIFICATION = `DELETE FROM NOTIFICATIONS WHERE ID = ?`;
export const DELETE_USER_ALL_NOTIFICATIONS = `DELETE FROM NOTIFICATIONS WHERE USER_ID = ?`;
export const GET_POST_USING_TITLE_USER_ID_TIME = `SELECT * FROM POSTS WHERE TITLE = ? AND USER_ID = ? AND CREATED_AT = ?`;
export const MERGE_INTO_POSTS = `MERGE INTO POSTS AF
        USING (VALUES(?,?,CAST('?' AS BLOB),?,?,?,?,?,?,?,?,?)) AS AFDATA(ID, TITLE, DESCRIPTION, CREATED_AT, USER_ID, CATEGORY_ID, IS_CLOSED, LAST_UPDATED_USER_ID, IS_DELETED, STATUS_ID, IS_FAQ, IS_REPORTED)
        ON AFDATA.ID = AF.ID
        WHEN MATCHED THEN UPDATE SET
            AF.TITLE = AFDATA.TITLE, 
            AF.DESCRIPTION = AFDATA.DESCRIPTION, 
            AF.CREATED_AT = AFDATA.CREATED_AT, 
            AF.USER_ID = AFDATA.USER_ID, 
            AF.CATEGORY_ID = AFDATA.CATEGORY_ID, 
            AF.IS_CLOSED = AFDATA.IS_CLOSED, 
            AF.LAST_UPDATED_USER_ID = AFDATA.LAST_UPDATED_USER_ID, 
            AF.IS_DELETED = AFDATA.IS_DELETED, 
            AF.STATUS_ID = AFDATA.STATUS_ID, 
            AF.IS_FAQ = AFDATA.IS_FAQ, 
            AF.IS_REPORTED = AFDATA.IS_REPORTED
        WHEN NOT MATCHED THEN INSERT(TITLE, DESCRIPTION, CREATED_AT, USER_ID, CATEGORY_ID, IS_CLOSED, LAST_UPDATED_USER_ID, IS_DELETED, STATUS_ID, IS_FAQ, IS_REPORTED) VALUES(AFDATA.TITLE, AFDATA.DESCRIPTION, AFDATA.CREATED_AT, AFDATA.USER_ID, AFDATA.CATEGORY_ID, AFDATA.IS_CLOSED, AFDATA.LAST_UPDATED_USER_ID, AFDATA.IS_DELETED, AFDATA.STATUS_ID, AFDATA.IS_FAQ, AFDATA.IS_REPORTED)`;
export const GET_POST_DETAILS_USING_POST_ID = `SELECT * FROM POSTS WHERE ID = ?`;
export const DELETE_POST_USING_POST_ID = `UPDATE POSTS SET IS_DELETED = TRUE WHERE ID = ?`;
export const CLOSE_POST_USING_POST_ID = `UPDATE POSTS SET IS_CLOSED = TRUE, STATUS_ID = (SELECT ID FROM TICKET_STATUS WHERE TRIM(UPPER(STATUS)) = 'CLOSED') WHERE ID = ?`;
export const TOGGLE_FAQ_ON_POST = `UPDATE POSTS SET IS_FAQ = CASE IS_FAQ WHEN TRUE THEN FALSE ELSE TRUE END WHERE ID = ?`;
export const TOGGLE_IS_REPORTED_ON_POST = `UPDATE POSTS SET IS_REPORTED = CASE IS_REPORTED WHEN TRUE THEN FALSE ELSE TRUE END WHERE ID = ?`;
export const UPDATE_TICKET_STATUS = `UPDATE POSTS SET STATUS_ID = ? WHERE ID = ?`;
export const MERGE_INTO_SAVED_POSTS = `MERGE INTO SAVED_POSTS TG 
        USING (VALUES (?,?,?,?)) AS TDATA (POST_ID, USER_ID, IS_DELETED, SAVED_AT) 
        ON TG.POST_ID = TDATA.POST_ID AND TG.USER_ID = TDATA.USER_ID 
        WHEN MATCHED THEN UPDATE SET 
            TG.IS_DELETED = TDATA.IS_DELETED, TG.SAVED_AT = TDATA.SAVED_AT
        WHEN NOT MATCHED THEN 
            INSERT (POST_ID, USER_ID, IS_DELETED, SAVED_AT) VALUES (TDATA.POST_ID, TDATA.USER_ID, TDATA.IS_DELETED, TDATA.SAVED_AT)`;
export const GET_USER_SAVED_DISCUSSIONS = `WITH COMMENT_COUNT AS ( SELECT COUNT(ID) AS COUNT, POST_ID FROM COMMENTS GROUP BY (POST_ID) ), 
        VOTE_COUNT AS ( SELECT COUNT(ID) AS COUNT, POST_ID FROM VOTES GROUP BY (POST_ID)), 
        TAG_VAL AS ( SELECT LISTAGG(TAG_NAME, '//') AS TAGS, POST_ID FROM TAGS WHERE IS_DELETED = FALSE GROUP BY (POST_ID) ), 
        SAVEDPOST AS ( SELECT TRUE AS IS_BOOKMARKED, POST_ID, SAVED_AT FROM SAVED_POSTS WHERE USER_ID = ? AND IS_DELETED = FALSE ), 
        VOTEPOST AS ( SELECT TRUE AS IS_VOTED, POST_ID FROM VOTES WHERE USER_ID = ?)   
        SELECT PO.ID, PO.TITLE, PO.DESCRIPTION, CA.ID AS CATEGORY_ID, CA.NAME AS CATEGORY, NVL(COM.COUNT,0) AS COMMENT_COUNT,   
            NVL(VO.COUNT,0) AS VOTE_COUNT, US.USER_ID,  NVL(SP.IS_BOOKMARKED, FALSE) AS IS_BOOKMARKED, NVL(VP.IS_VOTED, FALSE) AS IS_VOTED, 
            NVL(TV.TAGS,'') as TAGS, (US.FIRSTNAME || ' ' || US.LASTNAME) AS USER_NAME, PO.CREATED_AT, TS.STATUS, 
            COUNT(PO.ID) OVER ( ORDER BY PO.ID RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) TOTAL_COUNT 
        FROM POSTS PO LEFT JOIN CATEGORY CA ON PO.CATEGORY_ID = CA.ID 
        LEFT JOIN VOTE_COUNT VO ON PO.ID = VO.POST_ID 
        LEFT JOIN COMMENT_COUNT COM ON PO.ID = COM.POST_ID 
        LEFT JOIN USER US ON PO.USER_ID = US.USER_ID 
        LEFT JOIN TAG_VAL TV ON PO.ID = TV.POST_ID 
        INNER JOIN SAVEDPOST SP ON PO.ID = SP.POST_ID 
        LEFT JOIN VOTEPOST VP ON PO.ID = VP.POST_ID   
        LEFT JOIN TICKET_STATUS TS ON PO.STATUS_ID = TS.ID 
        WHERE  PO.IS_DELETED = 0 `;
export const RESET_ALL_TAGS = `UPDATE TAGS SET IS_DELETED = true WHERE POST_ID = ?`;
export const MERGE_INTO_TAGS = `MERGE INTO TAGS TG 
        USING (VALUES (?,?,?)) AS TDATA (POST_ID, TAG_NAME, IS_DELETED) 
        ON TRIM(LOWER(TG.TAG_NAME)) = TRIM(LOWER(TDATA.TAG_NAME)) AND TG.POST_ID = TDATA.POST_ID
        WHEN MATCHED THEN UPDATE SET 
            TG.POST_ID = TDATA.POST_ID,   
            TG.TAG_NAME = TDATA.TAG_NAME,
            TG.IS_DELETED = TDATA.IS_DELETED 
        WHEN NOT MATCHED THEN 
            INSERT (POST_ID, TAG_NAME, IS_DELETED) VALUES (TDATA.POST_ID, TDATA.TAG_NAME, TDATA.IS_DELETED)`;
export const CHECK_IS_VOTED = `SELECT * FROM VOTES WHERE USER_ID = ? AND POST_ID = ?`;
export const VOTE_POST = `MERGE INTO VOTES VT USING (VALUES (?, ?, ?)) AS VDATA (USER_ID, POST_ID, CREATED_AT) 
        ON VT.USER_ID = VDATA.USER_ID AND VT.POST_ID = VDATA.POST_ID 
        WHEN NOT MATCHED THEN 
        INSERT (USER_ID, POST_ID, CREATED_AT) VALUES (VDATA.USER_ID, VDATA.POST_ID, VDATA.CREATED_AT)`;
export const UNVOTE_POST = `DELETE FROM VOTES WHERE USER_ID = ? AND POST_ID = ?`;
export const UPDATE_USER_NAME = `UPDATE USER SET FIRSTNAME = ?, LASTNAME = ? WHERE EMAIL = ?`;
export const GET_ALL_ROLES = `SELECT * FROM ROLE`;
export const GET_ALL_AGENCY = `SELECT * FROM AGENCY`;
export const UPDATE_USER_ROLE_IN_AGENCY = `UPDATE USERINAGENCY SET ROLE_ID = ?, AGENCY_ID = ? WHERE USER_ID = ?`;
export const GET_USER_DISCUSSIONS = `WITH COMMENT_COUNT AS ( SELECT COUNT(ID) AS COUNT, POST_ID, MAX(CREATED_AT) AS CREATED_AT FROM COMMENTS GROUP BY (POST_ID) ), 
        VOTE_COUNT AS ( SELECT COUNT(ID) AS COUNT, POST_ID FROM VOTES GROUP BY (POST_ID)), 
        ADMIN_COMMENT_COUNT AS ( SELECT COUNT(CM.ID) AS COMMENT_COUNT, CM.POST_ID FROM COMMENTS CM LEFT JOIN USERINAGENCY US ON CM.USER_ID = US.USER_ID WHERE US.ROLE_ID = 1 GROUP BY (CM.POST_ID) ),
        TAG_VAL AS ( SELECT LISTAGG(TAG_NAME, '//') AS TAGS, POST_ID FROM TAGS WHERE IS_DELETED = FALSE GROUP BY (POST_ID) ),
        SAVEDPOST AS ( SELECT TRUE AS IS_BOOKMARKED, POST_ID FROM SAVED_POSTS WHERE USER_ID = ? AND IS_DELETED = FALSE ), 
        VOTEPOST AS ( SELECT TRUE AS IS_VOTED, POST_ID, CREATED_AT FROM VOTES WHERE USER_ID = ?)   
        SELECT PO.ID, PO.TITLE, PO.DESCRIPTION, CA.ID AS CATEGORY_ID, CA.NAME AS CATEGORY, NVL(COM.COUNT,0) AS COMMENT_COUNT, NVL(ACM.COMMENT_COUNT, 0) AS ADMIN_COMMENT_COUNT,
            NVL(VO.COUNT,0) AS VOTE_COUNT, US.USER_ID,  NVL(SP.IS_BOOKMARKED, FALSE) AS IS_BOOKMARKED, NVL(VP.IS_VOTED, FALSE) AS IS_VOTED, 
            NVL(TV.TAGS,'') as TAGS, (US.FIRSTNAME || ' ' || US.LASTNAME) AS USER_NAME, PO.CREATED_AT, TS.STATUS, COUNT(PO.ID) OVER ( ORDER BY PO.ID RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) TOTAL_COUNT 
            FROM POSTS PO LEFT JOIN CATEGORY CA ON PO.CATEGORY_ID = CA.ID 
            LEFT JOIN VOTE_COUNT VO ON PO.ID = VO.POST_ID 
            LEFT JOIN COMMENT_COUNT COM ON PO.ID = COM.POST_ID 
            LEFT JOIN ADMIN_COMMENT_COUNT ACM ON PO.ID = ACM.POST_ID 
            LEFT JOIN USER US ON PO.USER_ID = US.USER_ID 
            LEFT JOIN TAG_VAL TV ON PO.ID = TV.POST_ID 
            LEFT JOIN SAVEDPOST SP ON PO.ID = SP.POST_ID 
            LEFT JOIN VOTEPOST VP ON PO.ID = VP.POST_ID   
            LEFT JOIN TICKET_STATUS TS ON PO.STATUS_ID = TS.ID 
            WHERE (US.USER_ID = ? OR PO.ID IN (
                SELECT POST_ID FROM VOTES WHERE USER_ID = ?
                UNION ALL
                SELECT POST_ID FROM COMMENTS WHERE USER_ID = ? AND IS_DELETED = false
            )) AND PO.IS_DELETED = 0`;
